version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.9.0
      - image: circleci/redis:5.0.5
      - image: cypress/base:8

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
        keys:
        - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
        - v1-deps-{{ .Branch }}
        - v1-deps

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:

      # run tests!
      - run: yarn test
