version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.9.0
      - image: circleci/redis:5.0.5
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ~/.yarn
            - ~/.cache

      # run tests!
      - run: yarn test
