version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.9.0
      - image: cypress/base:12.4.0
        environment:
          # this enables colors in the output
          TERM: xterm

    working_directory: ~/repo

    steps:
      - checkout

      # - run:
      #     name: Cypress Dependencies
      #     command: sudo apt-get install xvfb libgtk-3-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.yarn
            - ~/.cache

      # run lint
      - run: yarn lint

      # run tests!
      # - run: yarn test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
