apiVersion: apps/v1
kind: Deployment
metadata:
  name: blag
  labels:
    app: blag
spec:
  replicas: 4
  selector:
    matchLabels:
      app: blag
  template:
    metadata:
      labels:
        app: blag
    spec:
      containers:
      - name: blag
        image: rg.fr-par.scw.cloud/nero/blag:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blag-svc
  labels:
    app: blag
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: blag
